### ISSUE TITLE
Slave agent can't be created after initial deployment of Jenkins

### ISSUE THREAD

**Issue by xscript** [Microsoft/movie-db-java-on-azure#30]
After the initial setup of Jenkins, slave agent can't be created by Kubernetes plugin. Below is the error message from Jenkins.
```
Connection #84 failed
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:216)
```

Work around is to save again at `configure system` page. Then slave agent can be created successfully afterwards.
Meanwhile, below is the error message when saving the configuration page.

```
Father of PodEnvVar [getValue()=36, getKey()=GROUP_SUFFIX] and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-needed-Post-build-action-doesn-t-stay-activated-td2308833.html
```

Initial suspect is this is a bug from Kubernetes plugin.

**Comment by ArchangelSDY** [comment]
As I'm not very familiar with the initialization process of this Jenkins instance, if you believe this is a bug from Jenkins Kubernetes Plugin you can file an issue directly at [Jenkins Jira](https://issues.jenkins-ci.org/issues/?jql=project+%3D+JENKINS+AND+component+%3D+kubernetes-plugin) and explain the details about how you use it.

You can also try [Azure Container Agents Plugin](https://github.com/jenkinsci/azure-container-agents-plugin) as an alternative.
